// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKaxmTMwkf0BK19DT4sEbjUlOGeOcIUhc',
    appId: '1:116722873660:web:a9332715e258054c839a39',
    messagingSenderId: '116722873660',
    projectId: 'crudfirebase-cb99a',
    authDomain: 'crudfirebase-cb99a.firebaseapp.com',
    storageBucket: 'crudfirebase-cb99a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfNb9bDCFPMw-KmRAdB1EmJq-6JFS8vQg',
    appId: '1:116722873660:android:a73000fb3b8a54c7839a39',
    messagingSenderId: '116722873660',
    projectId: 'crudfirebase-cb99a',
    storageBucket: 'crudfirebase-cb99a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL6kIUuse8DCqBFMRY9gr6McRFlTAhOzE',
    appId: '1:116722873660:ios:5be5fe08bb7b2d82839a39',
    messagingSenderId: '116722873660',
    projectId: 'crudfirebase-cb99a',
    storageBucket: 'crudfirebase-cb99a.appspot.com',
    iosBundleId: 'com.example.crudflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL6kIUuse8DCqBFMRY9gr6McRFlTAhOzE',
    appId: '1:116722873660:ios:191a242d1a4e5359839a39',
    messagingSenderId: '116722873660',
    projectId: 'crudfirebase-cb99a',
    storageBucket: 'crudfirebase-cb99a.appspot.com',
    iosBundleId: 'com.example.crudflutter.RunnerTests',
  );
}
